"""Initial migration

Revision ID: 50ba250a914d
Revises: 
Create Date: 2025-06-01 22:58:52.687955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ba250a914d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_set_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('disease', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('recommendation', sa.Text(), nullable=False))
        batch_op.drop_column('class_name')
        batch_op.drop_column('report')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_set_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('class_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('recommendation')
        batch_op.drop_column('disease')
        batch_op.drop_column('crop_name')

    # ### end Alembic commands ###
